spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/eClassOld
#    driver-class-name: org.h2.Driver
    url: jdbc:sqlserver://localhost:51433;database=eclass;encrypt=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: learn
    password: 1111

  devtools:
    livereload:
      enabled: true

  jpa:
    database: sql_server
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      location: #파일 저장 경로

  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace